### ISSUE TITLE
The `licensee detect` command gives error after initializing an empty git repository

### ISSUE THREAD

**Issue by ArniDagur** [licensee/licensee#312]
### Description of bug

`licensee detect` gives error after initializing an empty git repository

### Steps to reproduce the behavior

0.  `licensee detect` works fine with no git repository

```
[arni: LicenseeTest]$ ls
1stAncestor  LICENSE
```
```
[arni: LicenseeTest]$ licensee detect
License:        Apache-2.0
Matched files:  LICENSE
LICENSE:
  Content hash:  4579921419ac7db65117c87a46ad784f4a32bb01
  Confidence:    99.52%
  Matcher:       Licensee::Matchers::Dice
  License:       Apache-2.0
  Closest licenses:
    Apache-2.0 similarity:  99.52%
    ECL-2.0 similarity:     96.36%
    EPL-2.0 similarity:     57.20%
```
1. Initialize empty repo with `git init`
```
[arni: LicenseeTest]$ git init
Initialized empty Git repository in /home/arni/LicenseeTest/.git/
```
2. `licensee detect` gives error
```
[arni: LicenseeTest]$ licensee detect
Traceback (most recent call last):
        16: from /home/arni/.gem/ruby/2.5.0/bin/licensee:23:in `<main>'
        15: from /home/arni/.gem/ruby/2.5.0/bin/licensee:23:in `load'
        14: from /home/arni/.gem/ruby/2.5.0/gems/licensee-9.9.1/bin/licensee:37:in `<top (required)>'
        13: from /home/arni/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        12: from /home/arni/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        11: from /home/arni/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        10: from /home/arni/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         9: from /home/arni/.gem/ruby/2.5.0/gems/licensee-9.9.1/lib/licensee/commands/detect.rb:23:in `detect'
         8: from /home/arni/.gem/ruby/2.5.0/gems/licensee-9.9.1/lib/licensee/projects/project.rb:24:in `license'
         7: from /home/arni/.gem/ruby/2.5.0/gems/licensee-9.9.1/lib/licensee/projects/project.rb:147:in `licenses_without_copyright'
         6: from /home/arni/.gem/ruby/2.5.0/gems/licensee-9.9.1/lib/licensee/projects/project.rb:44:in `matched_files'
         5: from /home/arni/.gem/ruby/2.5.0/gems/licensee-9.9.1/lib/licensee/projects/project.rb:140:in `project_files'
         4: from /home/arni/.gem/ruby/2.5.0/gems/licensee-9.9.1/lib/licensee/projects/project.rb:55:in `license_files'
         3: from /home/arni/.gem/ruby/2.5.0/gems/licensee-9.9.1/lib/licensee/projects/git_project.rb:59:in `files'
         2: from /home/arni/.gem/ruby/2.5.0/gems/licensee-9.9.1/lib/licensee/projects/git_project.rb:38:in `commit'
         1: from /home/arni/.gem/ruby/2.5.0/gems/rugged-0.27.2/lib/rugged/repository.rb:22:in `last_commit'
/home/arni/.gem/ruby/2.5.0/gems/rugged-0.27.2/lib/rugged/repository.rb:22:in `head': reference 'refs/heads/master' not found (Rugged::ReferenceError)
```

**Comment by ArniDagur** [comment]
This bug is still present... What a terrible way of handling issues.

**Comment by ArniDagur** [comment]
😞

**Comment by ArniDagur** [comment]
😠

**Comment by atakanyenel** [comment]
@ArniDagur  PR #367 closes this issue. It is now merged to master, you can try it.
